// Raster_Laser_Projector_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module Raster_Laser_Projector_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                  //                                clk_0_clk.clk
		input  wire        Framebuffer_reset1_reset_bridge_in_reset_reset, // Framebuffer_reset1_reset_bridge_in_reset.reset
		input  wire        Video_In_reset_reset_bridge_in_reset_reset,     //     Video_In_reset_reset_bridge_in_reset.reset
		input  wire [31:0] Video_In_video_in_dma_address,                  //                    Video_In_video_in_dma.address
		output wire        Video_In_video_in_dma_waitrequest,              //                                         .waitrequest
		input  wire        Video_In_video_in_dma_write,                    //                                         .write
		input  wire [7:0]  Video_In_video_in_dma_writedata,                //                                         .writedata
		output wire [18:0] Framebuffer_s1_address,                         //                           Framebuffer_s1.address
		output wire        Framebuffer_s1_write,                           //                                         .write
		input  wire [7:0]  Framebuffer_s1_readdata,                        //                                         .readdata
		output wire [7:0]  Framebuffer_s1_writedata,                       //                                         .writedata
		output wire        Framebuffer_s1_chipselect,                      //                                         .chipselect
		output wire        Framebuffer_s1_clken                            //                                         .clken
	);

	wire         video_in_video_in_dma_translator_avalon_universal_master_0_waitrequest;   // Framebuffer_s1_translator:uav_waitrequest -> Video_In_video_in_dma_translator:uav_waitrequest
	wire   [7:0] video_in_video_in_dma_translator_avalon_universal_master_0_readdata;      // Framebuffer_s1_translator:uav_readdata -> Video_In_video_in_dma_translator:uav_readdata
	wire         video_in_video_in_dma_translator_avalon_universal_master_0_debugaccess;   // Video_In_video_in_dma_translator:uav_debugaccess -> Framebuffer_s1_translator:uav_debugaccess
	wire  [31:0] video_in_video_in_dma_translator_avalon_universal_master_0_address;       // Video_In_video_in_dma_translator:uav_address -> Framebuffer_s1_translator:uav_address
	wire         video_in_video_in_dma_translator_avalon_universal_master_0_read;          // Video_In_video_in_dma_translator:uav_read -> Framebuffer_s1_translator:uav_read
	wire   [0:0] video_in_video_in_dma_translator_avalon_universal_master_0_byteenable;    // Video_In_video_in_dma_translator:uav_byteenable -> Framebuffer_s1_translator:uav_byteenable
	wire         video_in_video_in_dma_translator_avalon_universal_master_0_readdatavalid; // Framebuffer_s1_translator:uav_readdatavalid -> Video_In_video_in_dma_translator:uav_readdatavalid
	wire         video_in_video_in_dma_translator_avalon_universal_master_0_lock;          // Video_In_video_in_dma_translator:uav_lock -> Framebuffer_s1_translator:uav_lock
	wire         video_in_video_in_dma_translator_avalon_universal_master_0_write;         // Video_In_video_in_dma_translator:uav_write -> Framebuffer_s1_translator:uav_write
	wire   [7:0] video_in_video_in_dma_translator_avalon_universal_master_0_writedata;     // Video_In_video_in_dma_translator:uav_writedata -> Framebuffer_s1_translator:uav_writedata
	wire   [0:0] video_in_video_in_dma_translator_avalon_universal_master_0_burstcount;    // Video_In_video_in_dma_translator:uav_burstcount -> Framebuffer_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (8),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (1),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (1),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (1),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) video_in_video_in_dma_translator (
		.clk                    (clk_0_clk_clk),                                                            //                       clk.clk
		.reset                  (Framebuffer_reset1_reset_bridge_in_reset_reset),                           //                     reset.reset
		.uav_address            (video_in_video_in_dma_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (video_in_video_in_dma_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (video_in_video_in_dma_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (video_in_video_in_dma_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (video_in_video_in_dma_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (video_in_video_in_dma_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (video_in_video_in_dma_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (video_in_video_in_dma_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (video_in_video_in_dma_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (video_in_video_in_dma_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (video_in_video_in_dma_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (Video_In_video_in_dma_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (Video_In_video_in_dma_waitrequest),                                        //                          .waitrequest
		.av_write               (Video_In_video_in_dma_write),                                              //                          .write
		.av_writedata           (Video_In_video_in_dma_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                     //               (terminated)
		.av_byteenable          (1'b1),                                                                     //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                     //               (terminated)
		.av_begintransfer       (1'b0),                                                                     //               (terminated)
		.av_chipselect          (1'b0),                                                                     //               (terminated)
		.av_read                (1'b0),                                                                     //               (terminated)
		.av_readdata            (),                                                                         //               (terminated)
		.av_readdatavalid       (),                                                                         //               (terminated)
		.av_lock                (1'b0),                                                                     //               (terminated)
		.av_debugaccess         (1'b0),                                                                     //               (terminated)
		.uav_clken              (),                                                                         //               (terminated)
		.av_clken               (1'b1),                                                                     //               (terminated)
		.uav_response           (2'b00),                                                                    //               (terminated)
		.av_response            (),                                                                         //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                     //               (terminated)
		.av_writeresponsevalid  ()                                                                          //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (19),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) framebuffer_s1_translator (
		.clk                    (clk_0_clk_clk),                                                            //                      clk.clk
		.reset                  (Framebuffer_reset1_reset_bridge_in_reset_reset),                           //                    reset.reset
		.uav_address            (video_in_video_in_dma_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (video_in_video_in_dma_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (video_in_video_in_dma_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (video_in_video_in_dma_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (video_in_video_in_dma_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (video_in_video_in_dma_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (video_in_video_in_dma_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (video_in_video_in_dma_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (video_in_video_in_dma_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (video_in_video_in_dma_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (video_in_video_in_dma_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (Framebuffer_s1_address),                                                   //      avalon_anti_slave_0.address
		.av_write               (Framebuffer_s1_write),                                                     //                         .write
		.av_readdata            (Framebuffer_s1_readdata),                                                  //                         .readdata
		.av_writedata           (Framebuffer_s1_writedata),                                                 //                         .writedata
		.av_chipselect          (Framebuffer_s1_chipselect),                                                //                         .chipselect
		.av_clken               (Framebuffer_s1_clken),                                                     //                         .clken
		.av_read                (),                                                                         //              (terminated)
		.av_begintransfer       (),                                                                         //              (terminated)
		.av_beginbursttransfer  (),                                                                         //              (terminated)
		.av_burstcount          (),                                                                         //              (terminated)
		.av_byteenable          (),                                                                         //              (terminated)
		.av_readdatavalid       (1'b0),                                                                     //              (terminated)
		.av_waitrequest         (1'b0),                                                                     //              (terminated)
		.av_writebyteenable     (),                                                                         //              (terminated)
		.av_lock                (),                                                                         //              (terminated)
		.uav_clken              (1'b0),                                                                     //              (terminated)
		.av_debugaccess         (),                                                                         //              (terminated)
		.av_outputenable        (),                                                                         //              (terminated)
		.uav_response           (),                                                                         //              (terminated)
		.av_response            (2'b00),                                                                    //              (terminated)
		.uav_writeresponsevalid (),                                                                         //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                      //              (terminated)
	);

endmodule
